# Demo of SmartComplete App
service: smartcomplete-svc
runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 2
  max_num_instances: 20
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5
health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 30
  unhealthy_threshold: 2
  healthy_threshold: 2